twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/bulma_layout.html.twig'
        - '@Autocomplete/autocomplete_form_theme.html.twig'
    globals:
        app_name: 'Pikaichu'

when@test:
    twig:
        strict_variables: true
