<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260826144513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Colonnes identité PostgreSQL (IDENTITY plutôt que SERIAL/sequence) requises par Doctrine DBAL 4.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dojos ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dojos ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN dojos.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN dojos.updated_at IS \'\'');
        $this->addSql('ALTER TABLE kyudojins ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE kyudojins ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN kyudojins.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN kyudojins.updated_at IS \'\'');
        $this->addSql('ALTER TABLE matches ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE matches ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN matches.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN matches.updated_at IS \'\'');
        $this->addSql('ALTER TABLE participants ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE participants ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN participants.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN participants.updated_at IS \'\'');
        $this->addSql('ALTER TABLE participating_dojos ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE participating_dojos ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN participating_dojos.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN participating_dojos.updated_at IS \'\'');
        $this->addSql('ALTER TABLE results ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE results ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN results.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN results.updated_at IS \'\'');
        $this->addSql('ALTER TABLE scoreboards ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE scoreboards ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN scoreboards.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN scoreboards.updated_at IS \'\'');
        $this->addSql('ALTER TABLE scores ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE scores ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN scores.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN scores.updated_at IS \'\'');
        $this->addSql('ALTER TABLE sessions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE sessions ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN sessions.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN sessions.updated_at IS \'\'');
        $this->addSql('ALTER TABLE staff_roles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE staff_roles ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN staff_roles.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN staff_roles.updated_at IS \'\'');
        $this->addSql('ALTER TABLE staffs ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE staffs ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN staffs.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN staffs.updated_at IS \'\'');
        $this->addSql('ALTER TABLE tachis ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tachis ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN tachis.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN tachis.updated_at IS \'\'');
        $this->addSql('ALTER TABLE taikai_events ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE taikai_events ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN taikai_events.created_at IS \'\'');
        $this->addSql('ALTER TABLE taikai_transitions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE taikai_transitions ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN taikai_transitions.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN taikai_transitions.updated_at IS \'\'');
        $this->addSql('ALTER TABLE taikais ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE taikais ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN taikais.start_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN taikais.end_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN taikais.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN taikais.updated_at IS \'\'');
        $this->addSql('ALTER TABLE teams ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE teams ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN teams.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN teams.updated_at IS \'\'');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN users.confirmed_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.confirmation_sent_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dojos ALTER id SET DEFAULT nextval(\'dojos_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dojos ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN dojos.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dojos.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE kyudojins ALTER id SET DEFAULT nextval(\'kyudojins_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE kyudojins ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN kyudojins.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN kyudojins.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE matches ALTER id SET DEFAULT nextval(\'matches_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE matches ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN matches.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN matches.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE participants ALTER id SET DEFAULT nextval(\'participants_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE participants ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN participants.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN participants.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE participating_dojos ALTER id SET DEFAULT nextval(\'participating_dojos_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE participating_dojos ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN participating_dojos.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN participating_dojos.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE results ALTER id SET DEFAULT nextval(\'results_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE results ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN results.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN results.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE scoreboards ALTER id SET DEFAULT nextval(\'scoreboards_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE scoreboards ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN scoreboards.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN scoreboards.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE scores ALTER id SET DEFAULT nextval(\'scores_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE scores ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN scores.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN scores.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE sessions ALTER id SET DEFAULT nextval(\'sessions_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE sessions ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN sessions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN sessions.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE staff_roles ALTER id SET DEFAULT nextval(\'staff_roles_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE staff_roles ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN staff_roles.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN staff_roles.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE staffs ALTER id SET DEFAULT nextval(\'staffs_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE staffs ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN staffs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN staffs.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE tachis ALTER id SET DEFAULT nextval(\'tachis_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE tachis ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN tachis.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tachis.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE taikai_events ALTER id SET DEFAULT nextval(\'taikai_events_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE taikai_events ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN taikai_events.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE taikai_transitions ALTER id SET DEFAULT nextval(\'taikai_transitions_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE taikai_transitions ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN taikai_transitions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN taikai_transitions.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE taikais ALTER id SET DEFAULT nextval(\'taikais_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE taikais ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN taikais.start_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN taikais.end_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN taikais.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN taikais.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE teams ALTER id SET DEFAULT nextval(\'teams_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE teams ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN teams.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN teams.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN users.confirmed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.confirmation_sent_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
